### ISSUE TITLE
Trained weight

### ISSUE THREAD

**Issue by Choneke** [djl11/PWC_Net_TensorFlow#1]
Thank you for making TensorFlow Version of PWC_Net.
Can you share your trained weight?
Also got the error when running main.py

![image](https://user-images.githubusercontent.com/39613742/42938082-0f681fc6-8b8c-11e8-9a02-75bf54b838de.png)
![image](https://user-images.githubusercontent.com/39613742/42938053-fabdee52-8b8b-11e8-9a57-8506655c011d.png)

**Comment by djl11** [comment]
Unfortunately I no longer have the trained weights saved! If you repeat the training process though I would be happy to add your trained weights to the repo.

As for the error, it appears as though the custom ops have not compiled correctly.
There can often be g++ issue for different versions/operating systems etc. with tf custom ops.

Can you tell me what the output for the nvcc and g++ commands are when run in the terminal as opposed to through python subprocess?
These are at lines 48 and 55 in [compiled.py](https://github.com/djl11/PWC_Net_TensorFlow/blob/master/custom_ops/compiled.py) respecitvely.
You need to have nvcc runnable from the command line, so the cuda/bin directory should be in your PATH variable.

If you are not using tf 1.8, cuda 9.0, and ubuntu 16.04 though, this is a gray area for me, and with the known difficulties with tf custom ops across different platforms, I will unfortunately have to close the issue.

**Comment by saxenarohan97** [comment]
@Choneke I have the same error, did you manage to solve it?

**Comment by NaifahNurya** [comment]
No, i didn't solve it. @saxenarohan97
