### ISSUE TITLE
Possible bug in optical flow estimator network

### ISSUE THREAD

**Issue by saxenarohan97** [djl11/PWC_Net_TensorFlow#2]
Hi @djl11,
Thanks for sharing your code.

The optical flow estimator network is a feed-forward network formed by stacking layers one over the other:
![image](https://user-images.githubusercontent.com/17175695/45503460-29874900-b787-11e8-9a71-12d058bed92d.png)

In the `flow_estimator_forward_pass` function, where the estimator network is defined, it says:
```
conv4 = tf.layers.conv2d(conv3,64,[3,3],(1,1),'same','channels_first',(1,1),tf.nn.leaky_relu)
ft = tf.layers.conv2d(conv4,32,[3,3],(1,1),'same','channels_first',(1,1),tf.nn.leaky_relu)
wt = tf.layers.conv2d(conv4,2,[3,3],(1,1),'same','channels_first',(1,1),tf.nn.leaky_relu)
```
That is, both ft and wt are stacked over `conv4`, instead of being stacked one over the other as in the figure from the paper. Was this intentional, or a bug?

**Comment by djl11** [comment]
It was a bug. Fixed now. Thanks for pointing this out!
